### ISSUE TITLE
Binaries & highlighting.

### ISSUE THREAD

**Issue by se16n** [varianus/ovonote#1]
Hello.

Great app.

Could you please upload binaries for windows under "releases"?

And feature request (if you accept them) custom color for priority, projects, contexts.

**Comment by varianus** [comment]
I've just done a binary release for Windows: [https://github.com/varianus/ovonote/releases/tag/v1.0](https://github.com/varianus/ovonote/releases/tag/v1.0)

The suggested features are quite interesting. 
At the moment I'm very busy at my job, but in the near future I'll try to implement them.
